services:
  api:
    build:
      context: .
    container_name: gravacoes_api
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
    networks:
      - gravacoes_network
    environment:
      NODE_ENV: production

networks:
  gravacoes_network:
    driver: bridge
