services:
  api:
    build: .
    container_name: gravacoes_api
    working_dir: /
    env_file:
      - stack.env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
    networks:
      - gravacoes_network
    environment:
      NODE_ENV: production

networks:
  gravacoes_network:
    driver: bridge
